version: '3'

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./links-postgres:/var/lib/postgresql/data
  rinkudesu-links:
    image: ghcr.io/rinkudesu/rinkudesu-links:latest
    depends_on:
      - postgres
    ports:
      - "80:80"
#      - "443:443"
    environment:
      RINKU_LINKS_CONNECTIONSTRING: "Server=postgres;Port=5432;Database=rinku-links;User Id=postgres;Password=postgres;"
      RINKUDESU_AUTHORITY: "https://<hostname-of-identity-instance>/"
      RINKU_KAFKA_ADDRESS: "<hostname-of-kafka>:9092"
      RINKU_KAFKA_CLIENT_ID: "rinkudesu-links"
      RINKU_KAFKA_CONSUMER_GROUP_ID: "rinkudesu-links"
      RINKUDESU_TAGS: "http://<host-of-tags-microservice>/api/v0/"
#      ASPNETCORE_URLS: "http://0.0.0.0:80;https://0.0.0.0:443"
#    volumes:
#      - ./cert.pfx:/app/cert.pfx:ro
    command:
      - "--applyMigrations"
