version: '3'

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./links-postgres:/var/lib/postgresql/data
  rinkudesu-links:
    image: ghcr.io/rinkudesu/rinkudesu-links:latest
    depends_on:
      - postgres
    build:
      context: ..
      dockerfile: Rinkudesu.Services.Links/Dockerfile
    ports:
      - "80:80"
    environment:
      RINKU_LINKS_CONNECTIONSTRING: "Server=postgres;Port=5432;Database=rinku-links;User Id=postgres;Password=postgres;"
      RINKUDESU_AUTHORITY: "https://<hostname-of-keycloak-instance>/realms/rinkudesu"
    command:
      - "--applyMigrations"
      - "-l 0"
